spring.application.name=GoodsOrder
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.url=jdbc:h2:tcp://localhost/~/../../java/db/GoodsOrder
spring.datasource.username=root
spring.datasource.password=pass

spring.sql.init.mode=always
spring.h2.console.enabled=true
